name: Test Runner

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Mostrar utilizador
        run: |
          whoami
          pwd
          hostname

      - name: Criar ficheiro de teste
        run: |
          mkdir -p /tmp/github-actions-test
          echo "Executado em $(date)" > /tmp/github-actions-test/teste.txt

      - name: Mostrar conteúdo
        run: |
          cat /tmp/github-actions-test/teste.txt
